### ISSUE TITLE
ImportError: cannot import name 'resources'

### ISSUE THREAD

**Issue by kennethkenneth** [pcko1/etherscan-python#24]
I get the following error when using the library:

```
$ python3 run_script.py
Traceback (most recent call last):
  File "run_script.py", line 1, in <module>
    from etherscan.accounts import Account
  File "/home/ubuntu/.local/lib/python3.6/site-packages/etherscan/__init__.py", line 1, in <module>
    from .etherscan import Etherscan
  File "/home/ubuntu/.local/lib/python3.6/site-packages/etherscan/etherscan.py", line 2, in <module>
    from importlib import resources
ImportError: cannot import name 'resources'
```

I use python 3.6 and installed the library with `pip3 install etherscan-python`.

**Comment by llmora** [comment]
If you are able to, use at least python v3.7, and the problem should disappear.

Alternative workarkiunds at https://github.com/ploomber/projects/issues/4

**Comment by Dlocc23** [comment]
Surely

**Comment by Dlocc23** [comment]
Surely

**Comment by Dlocc23** [comment]
Time

**Comment by Dlocc23** [comment]
Q

**Comment by Dlocc23** [comment]
> ``
