### ISSUE TITLE
 bash run_tests.sh My_api_key gives this kinda error 

### ISSUE THREAD

**Issue by rajeshkalakoti** [pcko1/etherscan-python#7]
======================================================================
FAIL: test_methods (test.test_modules.TestPro)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rk/Documents/etherscan-python/test/test_modules.py", line 33, in test_methods
    res = getattr(etherscan, fun)(**v["kwargs"])
  File "/home/rk/Documents/etherscan-python/etherscan/etherscan.py", line 33, in wrapper
    return parser.parse(r)
  File "/home/rk/Documents/etherscan-python/etherscan/utils/parsing.py", line 12, in parse
    assert status, f"{result} -- {message}"
AssertionError: Error! Missing Or invalid Action name -- NOTOK

**Comment by pcko1** [comment]
The **pro** methods are enabled only if you have a **pro** API key which you can request from etherscan.io.
